### ISSUE TITLE
Data format error

### ISSUE THREAD

**Issue by GitMonkey0** [microsoft/RespireNet#2]
Hi, I ran your code and it reported an error as follows

Original Traceback (most recent call last):
  File "/home/sata/zsb/miniconda/lib/python3.9/site-packages/torch/utils/data/_u                                                                                                                              tils/worker.py", line 287, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/sata/zsb/miniconda/lib/python3.9/site-packages/torch/utils/data/_u                                                                                                                              tils/fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/sata/zsb/miniconda/lib/python3.9/site-packages/torch/utils/data/_u                                                                                                                              tils/fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/zsb/LHT2/Feiyin/image_dataloader.py", line 248, in __getitem__
    audio = split_and_pad([audio, 0,0,0,0], self.desired_length, self.sample_rat                                                                                                                              e, types=1)[0][0]
  File "/home/zsb/LHT2/Feiyin/utils.py", line 120, in split_and_pad
    padded = generate_padded_samples(soundclip, soundclip, output_buffer_length,                                                                                                                               sample_rate, types); pad_times = (output_buffer_length-len(soundclip))/len(soun                                                                                                                              dclip)
  File "/home/zsb/LHT2/Feiyin/utils.py", line 176, in generate_padded_samples
    copy[:src_length] = source[:]
ValueError: setting an array element with a sequence. The requested array would                                                                                                                               exceed the maximum number of dimension of 1.

I really want to know why this error emerges, thank u!

**Comment by hvt1609** [comment]
You try this: https://github.com/microsoft/RespireNet/compare/main...hvt1609:RespireNet:patch-1
